CREATE TABLE clients (
    "_RowNumber" INTEGER,
    "Row ID" TEXT PRIMARY KEY,
    "Client ID" TEXT,
    "Назва" TEXT,
    "Населений пункт" TEXT,
    "Адреса" TEXT,
    "Локація" TEXT,
    "Власник" TEXT,
    "E-mail" TEXT,
    "Номер телефону" TEXT,
    "Контактна особа" TEXT,
    "Відстань" TEXT,
    "Related Tasks" TEXT[],
    "Related Project Images" TEXT[],
    "Related ProjectCostEstimates" TEXT[],
    "Related Route Installers" TEXT[],
    "Related Irrigation System Winterizations" TEXT[],
    "Related Spring Clients Lists" TEXT[],
    "Related ClientPayments" TEXT[],
    "Total Project Value" TEXT,
    "Total Paid" TEXT,
    "Remaining Balance" TEXT,
    "Projects List" TEXT[],
    "Info Balance" TEXT,
    "Info Finance" TEXT,
    "Related Routes By Start Point" TEXT[],
    "Related Routes By End Point" TEXT[],
    "Related Routes By Project Owner" TEXT[],
    "Related Route Filters" TEXT[],
    "Related Installation Equipments" TEXT[],
    "Related ClientsInvoices" TEXT[],
    "Related Route Works" TEXT[],
    "Related Projects" TEXT[]
);
