services:
  postgres:
    image: postgres:15
    container_name: aqua-postgres
    restart: always
    environment:
      POSTGRES_USER: aqua_user
      POSTGRES_PASSWORD: aqua_pass
      POSTGRES_DB: aqua_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    networks:
      - app-network

  migrate:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    command: npm run migrate
    environment:
      DATABASE_URL: postgres://aqua_user:aqua_pass@postgres:5432/aqua_db
    depends_on:
      - postgres
    restart: "no"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: aqua-server
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://aqua_user:aqua_pass@postgres:5432/aqua_db
    depends_on:
      - migrate
    networks:
      - app-network

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.client   # <-- multi-stage build for React + nginx
    container_name: aqua-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
