services:
  postgres:
    image: postgres:15
    container_name: aqua-postgres
    restart: always
    environment:
      POSTGRES_USER: aqua_user
      POSTGRES_PASSWORD: aqua_pass
      POSTGRES_DB: aqua_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  migrate:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    command: npm run migrate
    environment:
      DATABASE_URL: postgres://aqua_user:aqua_pass@postgres:5432/aqua_db
    depends_on:
      - postgres
    restart: "no"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: aqua-server
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://aqua_user:aqua_pass@postgres:5432/aqua_db
    depends_on:
      - migrate

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: aqua-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    container_name: aqua-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

volumes:
  postgres_data:
